name: Ruby

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - '3.2.2'

    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Set up PostgreSQL service
      run: |
        echo "Setting up PostgreSQL service..."
    - name: Run the default task
      run: bundle exec rake
      env:
        RAILS_ENV: test
        TEST_DATABASE: crumb_kit_test
        TEST_USERNAME: crumb_kit_user_test
        TEST_PASSWORD: test_password
        TEST_HOST: localhost
        TEST_PORT: 5432
        CI: true
    services:
      postgres:
        image: postgres:14
        ports: ['5432:5432']
        env:
          POSTGRES_USER: crumb_kit_user_test
          POSTGRES_PASSWORD: test_password
          POSTGRES_DB: crumb_kit_test
        options: >-
          --health-cmd pg_isready --interval 10s --timeout 5s --retries 5